# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Systems Research Lab
email: srl@srl.com
description: > # this means to ignore newlines until "baseurl:"
   The Systems Research Lab (SRL) is part of the Jack Baskin School of Engineering at the University of California, Santa Cruz. The SRL is interested in a broad range of topics including real-time systems, performance management, and large-scale storage systems. We are particularly interested in the intersection of these topics, and in their application to problems requiring inter-disciplinary collaboration. The SRL is composed of a broad range of students and collaborators from industry, government research labs, and other universities.


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://systems.soe.ucsc.edu" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  systemslab

# Build settings
markdown: kramdown

collections:
  news:
    output: true
    permalink: /:collection/:year/:month/:day/:title

  events:
    output: true
    permalink: /:collection/:year/:month/:day/:title

  people:
    output: true
    permalink: /:collection/:path/

  projects:
    output: true
    permalink: /:collection/:path/


  events:
    output: true
    permalink: /events/:path/

defaults:
  -
    scope:
      path: ""
      type: "news"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "people"
    values:
      layout: "person"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
  -
   scope:
      path: ""
      type: "sponsors"
   values:
      layout: "default"

scholar:
  style: apa
  locale: en

  sort_by: none
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"